//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.rolls = new HashSet<roll>();
        }
    
        public int Id { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string mailId { get; set; }
        public string phoneNumber { get; set; }
    
        public virtual ICollection<roll> rolls { get; set; }
    }
}
